# Generated by Django 3.1 on 2020-11-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201118_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sellMoney',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='moneyReceived',
            field=models.FloatField(null=True),
        ),
    ]
