# Generated by Django 3.1 on 2020-11-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specifications',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
