# Generated by Django 3.1 on 2020-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='specifications',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
